version: '3'
services:
  app:
    image: rick-n-morty
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+pymysql://root:test@database/rick_n_morty
    links:
      - db:database
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
        - data-volume:/var/lib/mysql
        
volumes:
  data-volume: